# Docker-compose configuration for development only

version: '3.4'

services:
    django:
        image: django
        build:
            context: .
            dockerfile: Dockerfile
        command: python ./manage.py runserver 0.0.0.0:3000
        ports:
            - "3000:3000"
        volumes:
            - "./backend:/app"
        depends_on:
            - postgres
        container_name: django

    postgres:
        image: postgres:12
        volumes:
            - ".data/postgres:/var/lib/postgresql/data"
        environment:
            POSTGRES_DB: challenge
            POSTGRES_USER: challenge
            POSTGRES_PASSWORD: challenge
        container_name: postgres
