# Generated by Django 3.2.8 on 2021-11-07 22:10

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_timestamp', models.DateTimeField(blank=True)),
                ('finish_timestamp', models.DateTimeField(blank=True)),
                ('tasks', models.ManyToManyField(to='tasks.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(verbose_name='Passed')),
                ('penalty_time', models.IntegerField(verbose_name='Penalty time')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                (
                'team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tournament',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_penalty_time', models.IntegerField(default=0)),
                ('total_tasks_passed', models.IntegerField(default=0)),
                ('results', models.ManyToManyField(to='tournaments.TournamentTaskResult')),
                (
                'team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tournament',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.TextField(default='')),
                ('used_hint', models.BooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task')),
                (
                'team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tournament',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(verbose_name='Success of the task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task')),
                (
                'team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tournament',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.tournament')),
            ],
        ),
    ]
