# Generated by Django 3.1.13 on 2021-11-04 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20211104_2023'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_hint', models.BooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentLeaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_penalty_time', models.IntegerField(default=0)),
                ('total_tasks_passed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentTaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(verbose_name='Passed')),
                ('penalty_time', models.IntegerField(verbose_name='Penalty time')),
                ('score', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task')),
            ],
        ),
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournamentattempt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='TournamentRating',
        ),
        migrations.AddField(
            model_name='tournamentleaderboard',
            name='results',
            field=models.ManyToManyField(to='tournaments.TournamentTaskResult'),
        ),
        migrations.AddField(
            model_name='tournamentleaderboard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentleaderboard',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='tournamenthint',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.tournament'),
        ),
    ]
