# Generated by Django 3.2.8 on 2021-10-31 02:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('hints', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=3)),
                ('x', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('y', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('answer', models.TextField()),
            ],
        ),
    ]
